apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: weather-service-disable-secret-access
  namespace: default
spec:
  selector:
    matchLabels:
      app: k8s-secret-example
  file:
    matchDirectories:
    - dir: /vol/
      recursive: true
    - dir: /proc/
      recursive: true
  action:
    Block
